name: release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  APP_NAME: 'promexplorer'
  NIM_VERSION: 'stable'
  MAINTAINER: 'Marcus Ramberg <marcus@means.no>'
  RELEASE_FILES: promexplorer LICENSE README.*
permissions:
  contents: write
jobs:
  build-artifact:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache choosenim
        id: cache-choosenim
        uses: actions/cache@v3.3.1
        with:
          path: ~/.choosenim
          key: ${{ runner.os }}-choosenim-${{ env.NIM_VERSION }}
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v3.3.1
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ env.NIM_VERSION }}
      - run: nimble build -Y -d:release
      - name: Create artifact
        run: |
          assets="${{ env.APP_NAME }}-${RUNNER_OS}-${GITHUB_REF_NAME}"
          echo "$assets"
          mkdir -p "dist/$assets"
          cp -r ${{ env.RELEASE_FILES }} "dist/$assets/"
          (
            cd dist
            if [[ "${{ runner.os }}" == Windows ]]; then
              7z a "$assets.zip" "$assets"
            else
              tar czf "$assets.tar.gz" "$assets"
            fi
            ls -lah *.*
          )
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ ENV.APP_NAME}}-${{runner.os}}
          path: |
            dist/*.tar.gz
            dist/*.zip

  create-release:
    runs-on: ubuntu-latest
    needs:
      - build-artifact
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: What did we get?
        run: |
          ls -la * */*
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            promexplorer-*/*.tar.gz
            promexplorer-*/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
